name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    env:
      RAILS_ENV: test
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Parallel Tests
      run: bin/rails test
      working-directory: test/dummy

    - name: Single Process Tests
      run: bin/rails test
      working-directory: test/dummy
      env:
        PARALLEL_TEST_THRESHOLD: "10000"

    - name: Run seeds
      run: bin/rails db:seed:replant
      working-directory: test/dummy

    - name: Rerun seeds
      run: bin/rails db:seed
      working-directory: test/dummy
